language: python

python:
    - "2.7"
cache: pip
install:
  - pip install selenium

addons:
  browserstack:
    username: "ashwingonsalves2"
    access_key:
      secure: "PVUe/vX/zcXqSmT+npyNF74LRNtJdvgaeLV+DKEYt7iLBO4zUWp9WTl7juxveui2thrD/X9c3/ZcmdFRmws0fjo68viwrPrmNrIZp8d1F/46H2lLiUmxCS+O8NU4BtlGqjYXPOgK9yZYBGXsnauOHL5IMasBlU9hZXtFSJRXhs6peJwcETT0dIGGyYL77O/jo5/PWscCHxtV1w6dY9xN9kbDvLHnrVujacsQpXsU50vHG6ILGJRsozF/SWawrMvTj5XLfYqEZmNd/J0PaUzqg7SHLdPXJPauhZFGAlzfXXQeYtqCmv3S6k0T+Osck5MoaP3rtUUq37koIJexaAdyTqhKnqbcNm7ZzOmzAYL1HNJKBakm/d4a5HcBEOaKqUEKJaSCU/TfxMRvNWzabb23ih7qlNYjKR288h3GpK4m1Ev01pkohmkLs1jcv/taJfv3JMaPVASo2o6G5yHhTcIDgSCagV/+eRx643GB4NGxWO1mcg3A32nKiBeH4r+0ZldzktBB2l/qNh19/xWN1YPcDymXBaSN1+jzNRhGUKVRsBK7zzhLDPzIZw9L2DeCUoonXie2NkESY3bcE2hUtb5bM6tspMTkR7+T3UmKBehEUALZ4Veell65dqD1AkwRgC4e+W2VhPdk1pXGUfrGFOtYMGO0HYwqq/YZhDQj/JrmCD0="

script:
  - python test.py
